[package]
name = "cli"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
logic = { path = "../.." }

serde = { version = "1.0" }
serde_json = "1.0"

thiserror = "1.0"
